<?php
/*
 *
 *       This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU Affero General Public License
 *     as published by the Free Software Foundation, either version 3 of
 *            the License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful, but
 *         WITHOUT ANY WARRANTY; without even the implied warranty of
 *        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *             GNU Affero General Public License for more details.
 *
 *      You should have received a copy of the GNU Affero General Public
 * License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
?>
<div id="settings_form" style="border: 1px solid #ccc; background: #eee; ">
<div style="padding: 20px;">
<div>
<fieldset>
<legend><h1><?php _e("StaticHomePage Help");?></h1></legend>

<h2><?php _e("What is the StaticHomePage Plugin?");?></h2>
<?php _e("StaticHomePage plugin allows you to show a static home page on your OSClass website intead of the normal dynamic page that is generated by OSClass.");?>

<h2><?php _e("Step #1 for installation:");?></h2>
<?php _e("The first thing you need to do in order to use StaticHomePage plugin, you need to edit the <font style=\"font-family:courier new;font-size:14px;\"><b>index.php</b></font> file in the root directory of your OSClass installation and add the function call <font style=\"font-family:courier new;font-size:14px;\"><b>statichomepage();</b></font> near the top of the page after the line with the following code, <font style=\"font-family:courier new;font-size:14px;\"><b>require_once ABS_PATH . 'oc-load.php' ;</b></font> as shown below (the code you need to add is highlighted in yellow): ");?><br/><br/>

<b>
<div style="border: 1px solid #333333; background-color: #ffffff; width: 400px;"><br/>
<font style="font-family:courier new;font-size:14px;">
require_once ABS_PATH . 'oc-load.php' ;<br/>
<span style="background-color:#ffff33;">statichomepage();</font><br/><br/>
</font>
</div>
</b>
<span>

<h2><?php _e("Step #2 for installation:");?></h2>
<?php _e("After inserting that one line of code above, then Create A Page in your &quot;Pages&quot; section of your OSClass system and give the page an Internal Name of <font style=\"font-family:courier new;font-size:14px;\"><b>_statichomepage</b></font>  (notice the underline character at the front of the Description and all lower case text). Now that page with the Internal Name of <font style=\"font-family:courier new;font-size:14px;\"><b>_statichomepage</b></font> is your new static home page. Voila!");?>


<h2><?php _e("How do I get back to the classified ads generated dynamically by OSClass?");?></h2>
<?php _e("After you have installed statichomepage plugin, you will want to create a link on your static page(s) to your OSClass classified ads dynamic homepage. To do this, you need add a link to your static page like this  <font style=\"font-family:courier new;font-size:14px; background-color:#ffff33;\"><b>http://www.yoursite.com/pathToOSClass/index.php?page=</b></font> and this will point to your OSClass dynamic homepage.");?>



</fieldset>
</div></div></div>
